# Generated by Django 3.0.5 on 2020-08-15 03:45

import core.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, null=True)),
                ('files', models.FileField(upload_to='documents')),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('rpta', models.BooleanField(default=False)),
                ('state', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('questions', djongo.models.fields.ArrayField(blank=True, model_container=core.models.Question, null=True)),
                ('answers', djongo.models.fields.EmbeddedField(blank=True, model_container=core.models.Answer, null=True)),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
            },
        ),
        migrations.CreateModel(
            name='modelQuestions',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, max_length=200, null=True)),
                ('weighted', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='plan',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('tittle', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('option1', models.CharField(max_length=50)),
                ('option2', models.CharField(max_length=50)),
                ('option3', models.CharField(max_length=50)),
                ('option4', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'planes',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('plan', models.CharField(max_length=200)),
                ('coin', models.CharField(max_length=200)),
                ('state', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
    ]
